// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/analyzer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkloadAnalyzer_AnalyzeWorkload_FullMethodName = "/analyzer.WorkloadAnalyzer/AnalyzeWorkload"
)

// WorkloadAnalyzerClient is the client API for WorkloadAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkloadAnalyzerClient interface {
	AnalyzeWorkload(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type workloadAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadAnalyzerClient(cc grpc.ClientConnInterface) WorkloadAnalyzerClient {
	return &workloadAnalyzerClient{cc}
}

func (c *workloadAnalyzerClient) AnalyzeWorkload(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, WorkloadAnalyzer_AnalyzeWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkloadAnalyzerServer is the server API for WorkloadAnalyzer service.
// All implementations must embed UnimplementedWorkloadAnalyzerServer
// for forward compatibility.
type WorkloadAnalyzerServer interface {
	AnalyzeWorkload(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedWorkloadAnalyzerServer()
}

// UnimplementedWorkloadAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkloadAnalyzerServer struct{}

func (UnimplementedWorkloadAnalyzerServer) AnalyzeWorkload(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeWorkload not implemented")
}
func (UnimplementedWorkloadAnalyzerServer) mustEmbedUnimplementedWorkloadAnalyzerServer() {}
func (UnimplementedWorkloadAnalyzerServer) testEmbeddedByValue()                          {}

// UnsafeWorkloadAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadAnalyzerServer will
// result in compilation errors.
type UnsafeWorkloadAnalyzerServer interface {
	mustEmbedUnimplementedWorkloadAnalyzerServer()
}

func RegisterWorkloadAnalyzerServer(s grpc.ServiceRegistrar, srv WorkloadAnalyzerServer) {
	// If the following call pancis, it indicates UnimplementedWorkloadAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkloadAnalyzer_ServiceDesc, srv)
}

func _WorkloadAnalyzer_AnalyzeWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadAnalyzerServer).AnalyzeWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadAnalyzer_AnalyzeWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadAnalyzerServer).AnalyzeWorkload(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkloadAnalyzer_ServiceDesc is the grpc.ServiceDesc for WorkloadAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkloadAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analyzer.WorkloadAnalyzer",
	HandlerType: (*WorkloadAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeWorkload",
			Handler:    _WorkloadAnalyzer_AnalyzeWorkload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/analyzer.proto",
}
